# 具体配置文档地址 https://github.com/lowlighter/metrics/blob/master/action.yml
# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference

name: GitHub metrics
on:
  schedule: 
      - cron: "0 0 * * *"
  workflow_dispatch:
  # push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # base metrics
      - name: base_metrics
        uses: lowlighter/metrics@latest
        with:
          filename: base_metrics.svg
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
          # Options
          user: ${{ github.repository_owner }}
          template: classic
          config_timezone: Asia/Shanghai
          committer_message: ":rocket: Update"
          base: header, activity, community, repositories, metadata
          plugin_traffic: yes
          plugin_lines: yes